### PR TITLE
Get Meals Endpoint

### PR DESCRIPTION
**Pull request by emcooper**
@case-eee I am having a hard time debugging an error in my test file.  I am getting the below errors when I run the test file and after some trial and error with a database spike file (will remove when done debugging) I think it is because the migrations did not run for the test database (when I change the spike file environment to 'test' it errors out exactly as below).  My knexfile.js is setup exactly like the lesson plan, and I double checked that the test database name is correct. I confirmed that the test section of knexfile.js is correctly referencing the migrations folder. Do you have any ideas on why this might be happening?

screen shot 2017-10-18 at 10 18 46 pm

### CODE REVIEW

**Comment by case-eee** [comment]
@emcooper sorry to hear you're running into so many problems getting your tests to work. one thing that comes to mind is that you're requiring your `configuration` and `database` in your test files directly and in your `server.js` file, but then you're also requiring it in your models themselves. you should only need to require it when you're directly using it.

this may be causing some weird errors? the rest of your code looks solid and all the syntax appears to be correct (in my opinion).

also - did you manually create the databases in `psql`? did you also double check that you ran the migrations?

last thought, i suggest moving `app.get('/api/v1/meals', Meals.getMeals)` above your `module.exports` in your `server.js` file!

let me know if none of these suggestions work 👍

**Comment by emcooper** [comment]
Yeah I'm almost positive it is due to the migrations not occurring for the test database. I've run them several times and it says it is using the development environment (see below). I'm wondering if there is a different command or setup needed to run them on the test environment? 

I looked back on the example from class and the same error is occurring. 

```
Ellens-MacBook-Pro:qs-backend ellencooper$ knex migrate:latest
Using environment: development
Already up to date
```

**Comment by emcooper** [comment]
Actually I think I figured it out, I had to run this: 
```
knex migrate:latest --env test
```

**Comment by emcooper** [comment]
@case-eee another issue I'm having is that PrjJS pauses only for a second, so you don't have time to actually use it unless you type super fast. Any thoughts?

**Comment by case-eee** [comment]
@emcooper i've never experienced that - sounds super strange! does it work like that everywhere or just in specific situations? also - are you getting any error messages?

**Comment by emcooper** [comment]
No error messages, and seems to be the same everywhere. It's ok though, I can just use the pg cli to play around with the code.

**Pull request closed without merging**
